[package]
name = "os"
version = "0.1.0"
edition = "2021"

# For minimising the binary size - taken from phil-opp's bootloader and https://github.com/johnthagen/min-sized-rust
[profile.dev]
panic = "abort"
opt-level = "s"
strip = true
codegen-units = 1
overflow-checks = false
lto = true

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
codegen-units = 1
overflow-checks = false
lto = true

[workspace]
members = ["bootloader", "bootstrapper", "kernel"]
