[package]
name = "bootloader"
version = "0.1.0"
edition = "2021"

[dependencies.common]
path = "../../lib/common"
features = ["panic"]

[dependencies.acpi]
path = "../../lib/acpi"

[dependencies.pci]
path = "../../lib/pci"
